# mybatis配置
mybatis:
  # mapper加载路径
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # mybatis配置文件
  config-location: classpath:mybatis-conf.xml

# 日志配置
logging:
  config: classpath:log4j2.xml

# spring配置
spring:
  application:
    name: hello-hust
  profiles:
    active: cloud
  mvc:
    converters:
      preferred-json-mapper: jackson
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 15MB
  # spring mail配置
  mail:
    host: smtp.163.com
    port: 465
    username: hust_hello@163.com
    password: JFKWQMXDUWRGLNZL
    protocol: smtps

server:
  servlet:
    encoding:
      charset: utf-8

# token配置
sa-token:
  token-name: hello-token     #token名称（同时也是cookie名称）
  timeout: 72000              #token有效期，单位s，默认30天，-1表示永不过期
  activity-timeout: -1        #token临时有效期（指定时间内无操作就视为token过期），单位s
  is-concurrent: true         #是否允许同一账号并发登录
  is-share: false             #多人登录同一账号时，是否共用一个token
  token-style: uuid           #token生成风格
  is-log: false               #是否输出日志
  is-read-head: true          #尝试从header中读取token

# BOS秘钥
BaiDuCloud:
  BOS:
    AK: 1e89d0b9d70442ac873f2e3259d2afce  # Access Key ID
    SK: 57866b4a24274b87bd10db25fd003e7e  # Secret Access Key
    EndPoint: http://gz.bcebos.com
    BucketName: hello-hust

